import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CarProvider } from '../context/CarContext';
import Sidebar from '../components/Sidebar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CarProvider> 
          <div className="flex">
            
            {/* 💡 1. SIDEBAR: Luôn hiện diện */}
            <Sidebar />
            {/* 💡 2. KHÔNG GIAN DÀNH CHO NỘI DUNG CHÍNH */}
            {/* Thêm padding-left bằng chiều rộng của Sidebar (w-60 -> pl-60) và chiều cao (min-h-screen) */}
            <div className="flex-grow min-h-screen pt-6 pl-60 bg-gray-50">
                {children}
            </div>

          </div>
        </CarProvider>
       
      </body>
    </html>
  );
}
